[gconnections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1uj8Vkw3uQn5GYy7LD7ADwXH3mtpvpZu2vQtiZ33yCXQ/edit?pli=1&gid=0#gid=0"
type = "service_account"
project_id = "tu-proyecto"
private_key_id = "tu-llave-id"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...\n-----END PRIVATE KEY-----\n"
client_email = "tu-servicio-cuenta@proyecto.iam.gserviceaccount.com"
